language: objective-c
osx_image: xcode10.1

addons:
  homebrew:
    packages:
    - carthage

env:
  matrix:
    - LANE=sdk_tests
    - LANE=lint_pod
    - LANE=lint_carthage

cache: bundler

before_install:
  - gem install bundler

script:
  - bundle exec fastlane $LANE
