language: objective-c

addons:
  homebrew:
    packages:
    - carthage

osx_image: 
- xcode10.3

env:
- LANE=sdk_tests SWIFT_VERSION=4.2
- LANE=sdk_tests SWIFT_VERSION=5.0
- LANE=lint_pod SWIFT_VERSION=4.2
- LANE=lint_pod SWIFT_VERSION=5.0
- LANE=lint_carthage

cache: bundler

before_install:
  - gem install bundler -v '2.0.1'

script:
  - bundle exec fastlane $LANE
