name: "LINE SDK CI"

on: [push, pull_request]

jobs:
  test_sdk:
    name: Test LINE SDK
    runs-on: macOS-latest
    strategy:
      matrix:
        swift-version: [5.0, 4.2]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Test SDK
        env:
          SWIFT_VERSION: ${{ matrix.swift-version }}
        run: bundle fastlane sdk_tests
  lint_pod:
    name: Lint CocoaPods
    runs-on: macOS-latest
    strategy:
      matrix:
        swift-version: [5.0, 4.2]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
    - name: Lint CocoaPods
      env:
        SWIFT_VERSION: ${{ matrix.swift-version }}
      run: bundle fastlane lint_pod
  lint_carthage:
    name: Lint Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Lint Carthage
        run: bundle fastlane lint_carthage
  xcframework:
    name: Build XCFramework
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build XCFramework
        run: bundle fastlane xcframework version:ci
